#!/usr/bin/env bash
# install HAproxy on the lb-01 server
# backup default haproxy configfile and create a new one with default configs

sudo apt-get -y install haproxy

server_config=\
"
frontend ngomane-alx-frontend
	 bind *:80
	 mode http
	 default_backend ngomane-alx-backend
backend ngomane-alx-backend
	mode http
	balance roundrobin
	server 115313-web-01 34.203.77.215:80 check
	server 115313-web-02 34.207.189.42:80 check
"

sudo echo "$server_config" >> /etc/haproxy/haproxy.cfg

#enable haproxy to be started by init script

sudo echo "ENABLED=1" >> /etc/default/haproxy

sudo service haproxy restart

