#!/usr/bin/env bash
#Write a Bash script that displays: To infinity and beyond indefinitely
#With a sleep 2 in between each iteration and I am invincible!!! when receiving a SIGTERM signal

function show()
{
	echo "I am invincible!!!"
}

while (( 1 )); do
		echo "To infinity and beyond"
		sleep 2
		trap show SIGTERM
done
