#!/usr/bin/env bash
#Prints a string and if statement

((num = 0))

while((num < 9))
do
    if [ $num -eq 8 ]
    then
        echo "Best School"
        echo "Hi"
    fi
    echo "Best School"
    ((num++))
done
