#!/usr/bin/env bash
#Prints a loop with nested if

((num = 1))

while((num < 11))
do
    if [ $num -eq 4 ]
    then
        echo "bad luck"
    elif [ $num -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((num++))
done
