#!/usr/bin/env bash
#Pints hours and minutes

time=0
hour=0
min=0
while [ $time -le 779 ]
do
        if [ $(( time % 60 )) -ne 0 ]
        then
                ((min=time%60))
                echo "$min"
        else
                echo "Hour: $hour"
                ((hour++))
        fi
        ((time++))
done 
