#!/usr/bin/env bash

# Retrieves list of all the network interfaces
interfaces=$(ifconfig -a | awk '/inet / {print $2}')

# Loop through each interface and display its IP address
for interface in $interfaces
do
  # Display the IP address
  echo "$interface"
done
