#!/usr/bin/env bash
#Retrieves list of all network interfaces
interfaces=$(ifconfig -a | awk '/inet / {print $2}')

# Loops through each interface and displays IP address
for interface in $interfaces
do
  #Show the IP address
  echo "$interface"
done
