#!/usr/bin/env bash

# Retrieves list of all network interfaces
interfaces=$(ifconfig -a | awk '/inet / {print $2}')

# Loop through each interface and display the IP address
for interface in $interfaces
do
  # Show the IP address
  echo "$interface"
done
